title: Jungbin Kim
description: Homepage
theme: just-the-docs

url: https://jungbinkim1.github.io

math: mathjax

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
